package mx.com.magmasoft.satp.vo;

// Generated 02-sep-2012 14:15:10 by Hibernate Tools 3.2.1.GA

/**
 * Agrupacionlaboral generated by hbm2java
 */
public class Agrupacionlaboral implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long serialVersionUID = 4085279512677840348L;
	private Integer idAgrupacionLaboral;
	private String razon;

	public Agrupacionlaboral()
	{
	}

	public Agrupacionlaboral(String razon)
	{
		this.razon = razon;
	}

	public Integer getIdAgrupacionLaboral()
	{
		return this.idAgrupacionLaboral;
	}

	public void setIdAgrupacionLaboral(Integer idAgrupacionLaboral)
	{
		this.idAgrupacionLaboral = idAgrupacionLaboral;
	}

	public String getRazon()
	{
		return this.razon;
	}

	public void setRazon(String razon)
	{
		this.razon = razon;
	}

}
