package mx.com.magmasoft.satp.vo;

// Generated 02-sep-2012 14:15:10 by Hibernate Tools 3.2.1.GA

/**
 * Ciudad generated by hbm2java
 */
public class Ciudad implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long serialVersionUID = 7932064387934728783L;
	private int idCiudad;
	private Estado estado;
	private String clave;
	private String nombre;

	public Ciudad()
	{
	}

	public Ciudad(int idCiudad, Estado estado)
	{
		this.idCiudad = idCiudad;
		this.estado = estado;
	}

	public Ciudad(int idCiudad, Estado estado, String clave, String nombre)
	{
		this.idCiudad = idCiudad;
		this.estado = estado;
		this.clave = clave;
		this.nombre = nombre;

	}

	public int getIdCiudad()
	{
		return this.idCiudad;
	}

	public void setIdCiudad(int idCiudad)
	{
		this.idCiudad = idCiudad;
	}

	public Estado getEstado()
	{
		return this.estado;
	}

	public void setEstado(Estado estado)
	{
		this.estado = estado;
	}

	public String getClave()
	{
		return this.clave;
	}

	public void setClave(String clave)
	{
		this.clave = clave;
	}

	public String getNombre()
	{
		return this.nombre;
	}

	public void setNombre(String nombre)
	{
		this.nombre = nombre;
	}

}
