package mx.com.magmasoft.satp.vo;

// Generated 02-sep-2012 14:15:10 by Hibernate Tools 3.2.1.GA

/**
 * Empresa generated by hbm2java
 */
public class Empresa implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1657937964465623574L;
	private int idEmpresa;
	private Agrupacionpersonas agrupacionpersonas;

	public Empresa()
	{
	}

	public Empresa(int idEmpresa, Agrupacionpersonas agrupacionpersonas)
	{
		this.idEmpresa = idEmpresa;
		this.agrupacionpersonas = agrupacionpersonas;
	}

	public int getIdEmpresa()
	{
		return this.idEmpresa;
	}

	public void setIdEmpresa(int idEmpresa)
	{
		this.idEmpresa = idEmpresa;
	}

	public Agrupacionpersonas getAgrupacionpersonas()
	{
		return this.agrupacionpersonas;
	}

	public void setAgrupacionpersonas(Agrupacionpersonas agrupacionpersonas)
	{
		this.agrupacionpersonas = agrupacionpersonas;
	}

}
