package mx.com.magmasoft.satp.vo;
// Generated 02-sep-2012 14:15:10 by Hibernate Tools 3.2.1.GA

import java.util.Set;

/**
 * Entidad generated by hbm2java
 */
public class Entidad implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long serialVersionUID = 7325720279105555738L;
	private Integer idEntidad;
	private String rfc;
	private Personafisica personafisica;
	private Personamoral personamoral;

	public Entidad()
	{
	}

	public Entidad(String rfc, Set<Telefono> telefonos, Set<Direccion> direccions, Personafisica personafisica, Personamoral personamoral, Set<Archivo> archivos)
	{
		this.rfc = rfc;
		this.personafisica = personafisica;
		this.personamoral = personamoral;
	}

	public Integer getIdEntidad()
	{
		return this.idEntidad;
	}

	public void setIdEntidad(Integer idEntidad)
	{
		this.idEntidad = idEntidad;
	}

	public String getRfc()
	{
		return this.rfc;
	}

	public void setRfc(String rfc)
	{
		this.rfc = rfc;
	}

	public Personafisica getPersonafisica()
	{
		return this.personafisica;
	}

	public void setPersonafisica(Personafisica personafisica)
	{
		this.personafisica = personafisica;
	}

	public Personamoral getPersonamoral()
	{
		return this.personamoral;
	}

	public void setPersonamoral(Personamoral personamoral)
	{
		this.personamoral = personamoral;
	}

}
