package mx.com.magmasoft.satp.vo;

// Generated 02-sep-2012 14:15:10 by Hibernate Tools 3.2.1.GA

/**
 * Licenciaconducir generated by hbm2java
 */
public class Licenciaconducir implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long serialVersionUID = 2237661476142912065L;
	private Integer idLicenciaConducir;
	private Chofer chofer;
	private Tipolicenciaconducir tipolicenciaconducir;
	private String clave;

	public Licenciaconducir()
	{
	}

	public Licenciaconducir(Chofer chofer,
			Tipolicenciaconducir tipolicenciaconducir)
	{
		this.chofer = chofer;
		this.tipolicenciaconducir = tipolicenciaconducir;
	}

	public Licenciaconducir(Chofer chofer,
			Tipolicenciaconducir tipolicenciaconducir, String clave)
	{
		this.chofer = chofer;
		this.tipolicenciaconducir = tipolicenciaconducir;
		this.clave = clave;
	}

	public Integer getIdLicenciaConducir()
	{
		return this.idLicenciaConducir;
	}

	public void setIdLicenciaConducir(Integer idLicenciaConducir)
	{
		this.idLicenciaConducir = idLicenciaConducir;
	}

	public Chofer getChofer()
	{
		return this.chofer;
	}

	public void setChofer(Chofer chofer)
	{
		this.chofer = chofer;
	}

	public Tipolicenciaconducir getTipolicenciaconducir()
	{
		return this.tipolicenciaconducir;
	}

	public void setTipolicenciaconducir(
			Tipolicenciaconducir tipolicenciaconducir)
	{
		this.tipolicenciaconducir = tipolicenciaconducir;
	}

	public String getClave()
	{
		return this.clave;
	}

	public void setClave(String clave)
	{
		this.clave = clave;
	}

}
