package mx.com.magmasoft.satp.vo;

// Generated 02-sep-2012 14:15:10 by Hibernate Tools 3.2.1.GA


/**
 * Pais generated by hbm2java
 */
public class Pais implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6025378484004838020L;
	private int idPais;
	private String clave;
	private String nombre;
	private String abreviatura;

	public Pais() {
	}

	public Pais(int idPais) {
		this.idPais = idPais;
	}

	public Pais(int idPais, String clave, String nombre, String abreviatura) {
		this.idPais = idPais;
		this.clave = clave;
		this.nombre = nombre;
		this.abreviatura = abreviatura;
	}

	public int getIdPais() {
		return this.idPais;
	}

	public void setIdPais(int idPais) {
		this.idPais = idPais;
	}

	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getAbreviatura() {
		return this.abreviatura;
	}

	public void setAbreviatura(String abreviatura) {
		this.abreviatura = abreviatura;
	}
}
