package mx.com.magmasoft.satp.vo;

// Generated 02-sep-2012 14:15:10 by Hibernate Tools 3.2.1.GA

/**
 * Tipodireccion generated by hbm2java
 */
public class Tipodireccion implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long serialVersionUID = -5822790245365691101L;
	private int idTipoDireccion;
	private String nombreTipo;

	public Tipodireccion()
	{
	}

	public Tipodireccion(int idTipoDireccion)
	{
		this.idTipoDireccion = idTipoDireccion;
	}

	public Tipodireccion(int idTipoDireccion, String nombreTipo)
	{
		this.idTipoDireccion = idTipoDireccion;
		this.nombreTipo = nombreTipo;
	}

	public int getIdTipoDireccion()
	{
		return this.idTipoDireccion;
	}

	public void setIdTipoDireccion(int idTipoDireccion)
	{
		this.idTipoDireccion = idTipoDireccion;
	}

	public String getNombreTipo()
	{
		return this.nombreTipo;
	}

	public void setNombreTipo(String nombreTipo)
	{
		this.nombreTipo = nombreTipo;
	}

}
