package mx.com.magmasoft.satp.vo;

// Generated 02-sep-2012 14:15:10 by Hibernate Tools 3.2.1.GA

/**
 * Tipotelefono generated by hbm2java
 */
public class Tipotelefono implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long serialVersionUID = 2248779137486046984L;
	private int idTipoTelefono;
	private String nombre;

	public Tipotelefono()
	{
	}

	public Tipotelefono(int idTipoTelefono)
	{
		this.idTipoTelefono = idTipoTelefono;
	}

	public Tipotelefono(int idTipoTelefono, String nombre)
	{
		this.idTipoTelefono = idTipoTelefono;
		this.nombre = nombre;
	}

	public int getIdTipoTelefono()
	{
		return this.idTipoTelefono;
	}

	public void setIdTipoTelefono(int idTipoTelefono)
	{
		this.idTipoTelefono = idTipoTelefono;
	}

	public String getNombre()
	{
		return this.nombre;
	}

	public void setNombre(String nombre)
	{
		this.nombre = nombre;
	}

}
