package mx.com.magmasoft.satp.vo;

// Generated 02-sep-2012 14:15:10 by Hibernate Tools 3.2.1.GA

/**
 * Tipoplaca generated by hbm2java
 */
public class Tipoplaca implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long serialVersionUID = 5119095339717903005L;
	private int idTipoPlaca;
	private String nombre;

	public Tipoplaca()
	{
	}

	public Tipoplaca(int idTipoPlaca)
	{
		this.idTipoPlaca = idTipoPlaca;
	}

	public Tipoplaca(int idTipoPlaca, String nombre)
	{
		this.idTipoPlaca = idTipoPlaca;
		this.nombre = nombre;
	}

	public int getIdTipoPlaca()
	{
		return this.idTipoPlaca;
	}

	public void setIdTipoPlaca(int idTipoPlaca)
	{
		this.idTipoPlaca = idTipoPlaca;
	}

	public String getNombre()
	{
		return this.nombre;
	}

	public void setNombre(String nombre)
	{
		this.nombre = nombre;
	}

}
