package mx.com.magmasoft.satp.vo;

// Generated 02-sep-2012 14:15:10 by Hibernate Tools 3.2.1.GA

/**
 * Tipolicenciaconducir generated by hbm2java
 */
public class Tipolicenciaconducir implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long serialVersionUID = -1513664713954367230L;
	private Integer idTipoLicenciaConducir;
	private String nombre;

	public Tipolicenciaconducir()
	{
	}

	public Tipolicenciaconducir(String nombre)
	{
		this.nombre = nombre;
	}

	public Integer getIdTipoLicenciaConducir()
	{
		return this.idTipoLicenciaConducir;
	}

	public void setIdTipoLicenciaConducir(Integer idTipoLicenciaConducir)
	{
		this.idTipoLicenciaConducir = idTipoLicenciaConducir;
	}

	public String getNombre()
	{
		return this.nombre;
	}

	public void setNombre(String nombre)
	{
		this.nombre = nombre;
	}

}
